# main의 application.yml
# spring.io -> Projects -> Spring Boot -> Learn -> spring ??? ?? reference ??
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2; # db url 경로
#    url : jdbc:h2:mem:test  # in-memory
#    url: jdbc:h2:tcp://localhost/~/jpashop2;MVCC=TRUE
    # 참고로 MVCC=TRUE 는 H2 1.4.200 버전부터 MVCC 옵션이 제거되었다. 그래서 이제는 제거해야 한다.
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 테이블을 drop하고 다시 만든다
      # none은 table drop안해서 한 번 데이터 넣어두면 db에 있는 데이터 그대로 쓸 수 있다.
    properties:
      hibernate:
        #show_sql: true  # ??? ??? ??? ??
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 쿼리 파라미터 로그 남기기