# main의 application.yml
# spring.io -> Projects -> Spring Boot -> Learn -> spring ??? ?? reference ??
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2; # db url 경로
#    url: jdbc:h2:tcp://localhost/~/jpashop2;MVCC=TRUE
    # 참고로 MVCC=TRUE 는 H2 1.4.200 버전부터 MVCC 옵션이 제거되었다. 그래서 이제는 제거해야 한다.
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # create 는 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
    properties:
      hibernate:
        #show_sql: true  # ??? ??? ??? ??
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 쿼리 파라미터 로그 남기기